development:
    adapter: mysql2
    encoding: utf8
    database: ruby
    username: obvious
    password: sushi
    host: 127.0.0.1
    port: 3306

production:
    adapter: mysql2
    encoding: utf8
    database: ruby
    username: obvious
    password: sushi
    host: 127.0.0.1
    port: 3306

test:
    adapter: mysql2
    encoding: utf8
    database: ruby_test
    username: obvious
    password: sushi
    host: 127.0.0.1
    port: 3306
